### ISSUE TITLE
Release tag

### ISSUE THREAD

**Issue by luizeof** [WPDevHQ/ElemenTemplater#2]
Thanks a lot for your time and support this plugin.

Please use a default for new releases through the git tags. It`s much easier to use your plugin and know if you are developing or testing some new version. We can also download the latest stable version. Thank you again!

**Comment by WPDevHQ** [comment]
Thanks for the pointer @luizeof 

Those were initial pain points in trying to get things right on the firts release - they had no major changes in term of development.

Will definatelly be tagging all future releases in order to keep things orderly :)

**Comment by luizeof** [comment]
@WPDevHQ  Thanks for you reply! This plugin is great! Thanks again.

**Comment by WPDevHQ** [comment]
Implemented.
